### PR TITLE
change to leading dot configuration rather then trailing

### PR DESCRIPTION
**Pull request by BenR1312**
We run into this error a lot:
`Place the . on the previous line, together with the method call receiver.`
Rather then this:
```
one.two.
  three
```

im suggesting we go back to what everyone likes doing in the first place which was
```
one.two
  .three
```

### CODE REVIEW

**Comment by wafendy** [comment]
Yes, please. Easier to move them around.

**Review by colynprater — APPROVED** [review]

**Review by wafendy — APPROVED** [review]

**Review by sathiyaseelan — APPROVED** [review]

**Review by yihyang — APPROVED** [review]

**Review by aniamoto — CHANGES_REQUESTED** [review]
Rejecting cause it doesn't meet current community standards. Are you sure, team? Can we talk about it? ;p

**Comment by aniamoto** [comment]
https://github.com/bbatsov/ruby-style-guide/pull/176
https://github.com/bbatsov/ruby-style-guide/issues/169#issuecomment-18669758


> Leading dots are an antipattern:
They require the continuation to be present at precisely next line. (I.e. you cannot put more than one in-line comment in between.)
They break mental context by requiring one to always analyze one more line of code.
Most importantly, code written with leading dots cannot be copied and pasted to irb/pry.

&&

> Also, putting . on the second line precludes intervening comments in any version.
```
1.to_i
  # failure
  .to_s
```
```
1.to_i.
  # success
  to_s
```

**Comment by wafendy** [comment]
We are MoneySmart community, we should have our own opinion and not following other people standard blindly.

**Comment by aniamoto** [comment]
@wafendy these are community standards, it's good to use them because there will be new devs joining and they might be used to them as well. Also, I copied some valid arguments against this change in my previous comments.

**Comment by wafendy** [comment]
In expense of ignoring our argument why this works for us.

**Comment by aniamoto** [comment]
@wafendy because of this change we won't be able to copy code blocks to irb/pry (which I think might be used quite often, at least I use it). I wish we could discuss it on the tech talk because the cons are quite high, so I wish everyone who approves it was familiar with what changes it brings.

**Comment by aniamoto** [comment]
@BenR1312 are you ok to talk about it? :)

**Comment by wafendy** [comment]
That's a valid argument, then I'm ok to use the default setting.

**Comment by kinmor06** [comment]
i got no problem with either, so long as we do it consistently. personal choice, i go with `trailing` with the chained call indented

**Comment by BenR1312** [comment]
https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains

> Adopt a consistent multi-line method chaining style. There are two popular styles in the Ruby community, both of which are considered good—leading . (Option A) and trailing . (Option B)

the resolution to https://github.com/bbatsov/ruby-style-guide/issues/169#issuecomment-18669758

the resolution to the above is to actually include the idea that both styles are good and either is fine amongst the community 
https://github.com/bbatsov/ruby-style-guide/commit/fefe83d3966e609efeec61f2f8481d6baf314ecc

@anna id like you to talk about this one at the tech talk in particular this is a good issue thats been raised and id rather not have to talk about other peoples issues for them at a tech talk.
ill put it on the board since we have that now.

The reason why these PR's get put up in the first place is to act as a catalyst for discussion so if we think we need to talk about it further lets do that!

**Comment by BenR1312** [comment]
We spoke about this at our Tech Talk and decided the benefits of the trailing dot far far outweigh the style preference of the leading dot.
Thanks to @aniamoto for bringing these points up.

**Pull request closed without merging**
